### ISSUE TITLE
KScrash over Cocapods does not compile when using the use_frameworks! flag

### ISSUE THREAD

**Issue by badgercl** [kstenerud/KSCrash#102]
Hi,

KSCrash started throwing compilation errors after I updated my Podfile with the use_frameworks! flag at the beginning of the file.

I get 2 errors with the same message: "ARC forbids Objective-C objects in union/struct".

* KSMachApple.h
![screen shot 2015-10-08 at 5 04 14 pm](https://cloud.githubusercontent.com/assets/4398862/10378333/22e65970-6de7-11e5-8d0b-225834e0fe9b.png)
* KSObjCApple.h
![screen shot 2015-10-08 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/4398862/10378334/25b66a32-6de7-11e5-8a07-4f6c94b1d130.png)

Because of these errors the library does not compile and cannot be used in the main project.

I think I can work without the flag since none of the other libs are also written in Obj-C, but I won't be able to use Swift libs.

I'm running the code in Xcode 7.0.1 (latest stable version) in OS X 10.11.

Here's a basic project I used to replicate the problem: https://www.dropbox.com/s/ngierzuqmtvest1/KSCrashFramework.zip?dl=0

1. Open KSCrashFramework.xcworkspace (since it is a Cocoapod projeect)
2. Open ```Podfile``` and make sure the flash *use_frameworks!* is uncommented.
3. Press cmd+shift+alt+K to clean the build folder.
4. Press cmd+B to build the project.

There should be 3 errors: the two mentioned above and a third on AppDelegate.m.

Now follow these steps:
5. Go to Podfile and comment *use_frameworks!* using # and save.
6. Open the Terminal and go to the project folder.
7. Run ``pod install``
8. Press cmd+shift+alt+K to clean the build folder.
9. Press cmd+B to build the project.

The project builds!

**Comment by kstenerud** [comment]
OK, give these changes a try:

in `KSMachApple.h` line 168:
- change `dispatch_queue_t` to `uintptr_t`

in `KSObjCApple.h` line 428 and 429:
- change `id` to `uintptr_t`

That should fix everything except the macro redefinition warning. Let me know if that creates a library that works, and I'll incorporate the changes into mainline.

**Comment by badgercl** [comment]
I've included the changes, compiled the project with use_frameworks! enabled and forced an exception. Everything worked well. Thanks!

**Comment by kstenerud** [comment]
Updated in latest commit.
