### ISSUE TITLE
How to determine two crashes are the same crash?

### ISSUE THREAD

**Issue by xieweizhi** [kstenerud/KSCrash#103]
Is there a key or something to do that?

**Comment by kstenerud** [comment]
The only way to determine that would be to compare the stack traces for similarities.

**Comment by xieweizhi** [comment]
@kstenerud  Thanks

**Comment by ZhangDihan** [comment]
hi, do you find an elegant way to judge two crashes are same reason?

**Comment by ZhangDihan** [comment]
hi, do you find an elegant way to judge two crashes are same reason?
"compare the stack traces" should compare all or just compare crash thread?
thanks anyway!
