### ISSUE TITLE
一直显示未激活是什么情况？

### ISSUE THREAD

**Issue by lexiaoyao20** [kstenerud/KSCrash#107]
是不是没有收集到crash报告，就会显示未激活？ 还是 调用install方法就会激活啊？

下面是我的代码：
KSCrashInstallationHockey* installation = [KSCrashInstallationHockey sharedInstance];
    installation.appIdentifier = BugHDKey;
    [installation install];
    [installation sendAllReportsWithCompletion:nil];

**Comment by kelp404** [comment]
English please
