### ISSUE TITLE
Problem with Crash in Handler

### ISSUE THREAD

**Issue by dirtmelon** [kstenerud/KSCrash#114]
when I tried to test the "crash in handler" exception in the Crash-Tester,the demo didn't flash back.it jammed.It can record the crash report.But just didn't flash back.I tested in iPhone 6s,iOS 9.2.1.

**Comment by dirtmelon** [comment]
can the demo flash back when the "crash in handler" exception happen?thank you.I am a novice iOS development.

**Comment by kstenerud** [comment]
There seems to have been a change in iOS such that a crash in the crash handler locks up the app. I haven't figured out why, but so far I do know that the crash handlers don't even get called when a second crash occurs.

I'll be continuing my investigation.

**Comment by dirtmelon** [comment]
Thank you very much.KSCrash is a very cool third party！
I had tested some demo include KSCrash and other sdk which are be able to handler crash.(the SDK from China).if KSCrash init after the other sdk,when the crash happen,the app locks up.I found the KSCrashSentry_NSException.m used the `kscrashsentry_suspendThreads()` but didn't use `kscrashsentry_resumeThreads()`,I tried to add `kscrashsentry_resumeThreads()` after `        kscrashsentry_uninstall(KSCrashTypeAll);`,the app didn't locks up when the crash happen.
another question is today i update the KSCrash with cocoa pods,I found some headers convert to project(),such as KSCrashAdvanced.h transform form public to project,it made me can't import KSCrashAdvanced in my project...
At last,thank you for your reply to me,I type this with google translate.Hope you can understand^_^
