### ISSUE TITLE
duplicate symbol ___cxa_throw

### ISSUE THREAD

**Issue by yvasileuski** [kstenerud/KSCrash#121]
duplicate symbol ___cxa_throw in:
    <my project path>/Build/Products/Debug-iphonesimulator/libKSCrash.a(KSCrashSentry_CPPException.o)
    <my project path>/MyProject(CPPExceptionHandler.o)

ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It seems there is no way to use KSCrash with another build-in crash handler due to "duplicate symbol ___cxa_throw". At the same time Crashlitics does not have such problem.

Is it possible to apply another approach to handle cpp crashes?

**Comment by yvasileuski** [comment]
Is there any update? If application uses  ___cxa_throw for cpp crash handling by itself, it is impossible to use KSCrash as additional crash handler. However, there is no such problem with Crashlitics as additional crash handler.

**Comment by kstenerud** [comment]
I'm still not sure how to tackle this. The normal way to use `__cxa_throw` is to override it in user code, and then the linker just picks the user version during the runtime linking phase if it's present. But if the symbol is present multiple times in user code it will cause a static linker fail. Maybe there might be a way to dynamically relink at runtime?

**Comment by yvasileuski** [comment]
Have you studied Crashlitics approach?

**Comment by kstenerud** [comment]
Their code is closed source as far as I know.

**Comment by kstenerud** [comment]
Oh wait... I may have an idea...

**Comment by kstenerud** [comment]
OK, I've done this: https://github.com/kstenerud/KSCrash/commit/4cf81a377097ec88b4146a7da07cc00924a8ff31

That's the best I can do unless there's some way to capture all possible implementations of a function at runtime AND be the one to control the master linkage.

**Comment by yvasileuski** [comment]
Thank you, it seems to work, at least it is possible to compile multiple instances.
