### ISSUE TITLE
Dependency "KSCrash" has no shared framework schemes for any of the platforms: Mac

### ISSUE THREAD

**Issue by sebastianvarela** [kstenerud/KSCrash#131]
Hi! 
I want to use KSCrash with carthage, please, it is possible to add a shared scheme/support for Mac? :)

**Comment by kstenerud** [comment]
All major targets should be shared on both iOS and Mac.

![screen shot 2016-03-10 at 1 38 16 pm](https://cloud.githubusercontent.com/assets/245857/13685453/6454708e-e6c5-11e5-9caa-f6437e9fa00a.png)
