### ISSUE TITLE
Major version was removed and KSCrashReportFilterAppleFmt need to be updated.

### ISSUE THREAD

**Issue by waynegreen** [kstenerud/KSCrash#135]
In Class:KSCrashReport.c
the values:
`#define kReportVersionMajor 3
#define kReportVersionMinor 0`
was removed.
and the value of key:KSCRASH_REPORT_VERSION is String now
`void kscrw_i_writeReportInfo(const KSCrashReportWriter* const writer,
                             const char* const key,
                             const char* const type,
                             const char* const reportID,
                             const char* const processName)
{
    writer->beginObject(writer, key);
    {
        writer->addStringElement(writer, KSCrashField_Version, KSCRASH_REPORT_VERSION);
        writer->addStringElement(writer, KSCrashField_ID, reportID);
        writer->addStringElement(writer, KSCrashField_ProcessName, processName);
        writer->addIntegerElement(writer, KSCrashField_Timestamp, time(NULL));
        writer->addStringElement(writer, KSCrashField_Type, type);
    }
    writer->endContainer(writer);
}
`
but in class:KSCrashReportFilterAppleFmt.m the value is not get in new way.
`- (int) majorVersion:(NSDictionary*) report
{
    NSDictionary* info = [self infoReport:report];
    NSDictionary* version = [info objectForKey:@KSCrashField_Version];
    return [[version objectForKey:@KSCrashField_Major] intValue];
}`
and this method maybe also need to be updated:
`- (void) filterReports:(NSArray*) reports
          onCompletion:(KSCrashReportFilterCompletion) onCompletion
{
    NSMutableArray* filteredReports = [NSMutableArray arrayWithCapacity:[reports count]];
    for(NSDictionary* report in reports)
    {
        if([self majorVersion:report] == kExpectedMajorVersion)
        {
            [filteredReports addObjectIfNotNil:[self toAppleFormat:report]];
        }
    }

    kscrash_i_callCompletion(onCompletion, filteredReports, YES, nil);
}`

**Comment by kstenerud** [comment]
Should be fixed in latest version (1.2.1)
