### ISSUE TITLE
KSCrashAdvanced.h and KSCrashReportStore.h are not public in 1.2.1

### ISSUE THREAD

**Issue by daniilkorotin** [kstenerud/KSCrash#136]
Hey. I need to access the crash report storage to compose and send my own combined logs. KSCrashAdvanced.h exposes the KSCrashReportStore class I need, however both are not public anymore. Could you please fix that or point me to a workaround. Thanks!
P.S. I use CocoaPods installation.

**Comment by kstenerud** [comment]
To use `KSCrashAdvanced.h`, you'll need to specify it in your podfile:

```ruby
pod 'KSCrash', :subspecs => ['Installations', 'RecordingAdvanced']
```

**Comment by daniilkorotin** [comment]
Thanks. Where can I read about the other subspecs?

**Comment by kstenerud** [comment]
If you look inside `KSCrash.podspec` you can see which headers are associated with which subspec.
