### ISSUE TITLE
Enable crash logging in debugger

### ISSUE THREAD

**Issue by ATS-RyanPowell** [kstenerud/KSCrash#157]
Is there a way to enable crash logging with the debugger attached.

Im getting message:
```
KSCrash: App is running in a debugger. The following crash types have been disabled:
* KSCrashTypeMachException
* KSCrashTypeNSException
```

However I cannot find any references to this text in this project.

I've tried building this project on to a device with the debugger disabled (get-task-allow=false in entitlements). However I am still seeing no evidence the crash is getting logged.

I need to be able to investigate why my app crashes aren't being logged on HockeyApp however I cannot  investigate until I disable the above.

Using version 1.5.7

Any ideas?

**Comment by kstenerud** [comment]
It's in KSCrashSentry.c, line 109:

```c
KSCrashType kscrashsentry_installWithContext(KSCrash_SentryContext* context,
                                             KSCrashType crashTypes,
                                             void (*onCrash)(void))
{
    if(ksmach_isBeingTraced())
    {
        KSLOGBASIC_WARN("KSCrash: App is running in a debugger. Only user reported events will be handled.");
        crashTypes = KSCrashTypeNone;
```

Bear in mind that disabling this check can cause Xcode's debugger to not trigger exception breakpoints at the right place for some things.

**Comment by ATS-RyanPowell** [comment]
Thanks for the prompt response.

You are correct. 

Overriding ksmach_isBeingTraced to return 0 forces the crash logger on.

**Comment by loumzy** [comment]
It was not work for me, I create a exception by the method below,but It still can not be caught.
```
     NSString *searchKeys;
     [self.searchKeys addObject:searchKeys];

```
