### ISSUE TITLE
Add ability to submit additional information in time when user submits crash report

### ISSUE THREAD

**Issue by iThinker** [kstenerud/KSCrash#186]
My application gathers logs, and I would like to send those logs with crash report. I use email for crash report submission.
I might use custom crash creation, but I need to do it only if there is crash. If there is no crash, I don't want to treat logs as crash.
Thanks in advance.

**Comment by kstenerud** [comment]
Create a custom crash callback:
```objc
static void onCrash(const KSCrashReportWriter* writer)
{
    writer->addTextFileElement(writer, "my_log_file", "/path/to/logfile.txt");
}
```
Register the callback:
```objc
    KSCrashInstallationEmail* emailInstallation = [KSCrashInstallationEmail sharedInstance];
    ...
    emailInstallation.onCrash = onCrash;
```
When it crashes, it will read `/path/to/logfile.txt` and add its contents to the field `my_log_file` in the `user` section of the crash report.

**Comment by iThinker** [comment]
Great. Thank you.
Does it work only with JSON report style?
I don't see my information with Apple style reports. What tool can I use to better analyze json crash reports?

**Comment by iThinker** [comment]
@kstenerud my latest question is kind of actual. :( It is hard to work with json crashes. But I want to have logs attached.
