### ISSUE TITLE
compile error on iPhone6P

### ISSUE THREAD

**Issue by zymxxx** [kstenerud/KSCrash#188]
<img width="943" alt="qq20161223-0 2x" src="https://cloud.githubusercontent.com/assets/6263633/21449099/a0f1c586-c924-11e6-9390-e329739d4155.png">

cocoapods、xcode8.2

**Comment by kstenerud** [comment]
Which file is this?
What release are you using?

**Comment by zymxxx** [comment]
KSCPU_arm.c
version: 1.13.0

**Comment by kstenerud** [comment]
I'm not seeing this in my setup.
What environment are you using? Are you using cocoapods? Are you building one of the crash tester apps?

**Comment by zymxxx** [comment]
the same code use version(1.11.2) is ok, above the version is error.

the cocoapod's version is 1.1.1

**Comment by chrisballinger** [comment]
I am also seeing this error using CocoaPods w/ 1.13.1. Only during production builds though (???).

**Comment by kstenerud** [comment]
Bleh there were some leftover files that cocoapods was picking up. Pushing 1.13.2 now with them removed.

**Comment by zymxxx** [comment]
thanks~
