### ISSUE TITLE
Application crashes on startup when run on iPhone5 and below (32bit)

### ISSUE THREAD

**Issue by andypraneet** [kstenerud/KSCrash#196]
Hello,

I have this crash on iPhone5 and below running on 32bit, although I enabled all architectures while building the project using the framework which was also built to run on all archs.

I get the below on startup on iPhone5 and below -

Sample[13338:12431649] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM safeSetObject:forKey:]: unrecognized selector sent to instance 0x79d6aa80'
*** First throw call stack:
(
	0   CoreFoundation                      0x07788212 __exceptionPreprocess + 194
	1   libobjc.A.dylib                     0x07190e66 objc_exception_throw + 52
	2   CoreFoundation                      0x078013dc -[NSObject(NSObject) doesNotRecognizeSelector:] + 172
	3   CoreFoundation                      0x0770734c ___forwarding___ + 1052
	4   CoreFoundation                      0x07706f0e _CF_forwarding_prep_0 + 14
	5   Sample                              0x00655121 +[KSSystemInfo systemInfo] + 289
	6   Sample                              0x00655f0a kssysteminfo_toJSON + 58
	7   Sample                              0x0066305e kscrash_install + 158
	8   Sample                              0x0066f8d1 -[KSCrash install] + 337
	9   Sample                              0x0064c5fa -[KSCrashInstallation install] + 202

**Comment by kstenerud** [comment]
You need to set `-objc` in the linker flags.

**Comment by andypraneet** [comment]
Hi kstenerud,

I have already put the -objc flag but still it doesnt work on iphone5 and below.
I am creating a kscrashlib and using it in my project.
In both the projects, -objc is enabled in linker flags.

Am I missing something?

**Comment by andypraneet** [comment]
I downloaded your latest commit and all is well.
Was on a six month old code.

Thanks a ton!
