### ISSUE TITLE
Support of Jetsam/LowMemory reports?

### ISSUE THREAD

**Issue by drach** [kstenerud/KSCrash#202]
Hi,

Does KSCrash support reporting of Jetsam/LowMemory crash logs? I haven't found any mention of it in the repository. It would be a nice feature to have for cases of big games that struggle to balance between on-device memory restrictions and HD graphics requirements.

A few examples of reports: http://pastebin.com/raw/LU4anXJD, http://pastebin.com/raw/gVvMHDeA, http://pastebin.com/raw/A8GpH35w

Thank you

**Comment by kstenerud** [comment]
Unfortunately, no. Low memory process shutdown happens entirely outside of the application, so there's no way to trap it.

**Comment by drach** [comment]
Understood, thanks a lot!
