### ISSUE TITLE
KSCrash Query

### ISSUE THREAD

**Issue by 74981** [kstenerud/KSCrash#231]
Hi, I dont know if i am asking some silly question but i would like to know can we avoid app termination when crash happen? Please let me know.

**Comment by kstenerud** [comment]
When the app experiences a fatal error, it's impossible to know the app state, or what's safe to call, aside from async-safe functions. Calling any C++, Objective-C, Swift, or even C code that triggers memory or resource allocations can and do cause a complete app lockup.

So while it's technically possible to avoid app termination on a crash, you really don't want to do that.

If you REALLY want to keep the app alive, don't return from the onCrash function. But seriously, don't do that. You'll have a lot of angry users with frozen apps.

**Comment by 74981** [comment]
I was looking for OnCrash function but could not get. Can you please let me know file name where i could find OnCrash function and can check where it return.
