### ISSUE TITLE
#232 OnCrash Details needed

### ISSUE THREAD

**Issue by 74981** [kstenerud/KSCrash#233]
#232  I was looking for OnCrash function but could not get. Can you please let me know file name where i could find OnCrash function and can check where it return.

**Comment by kstenerud** [comment]
```objc
static void myCrashHandler(const KSCrashReportWriter* writer)
{
    // Do your crash hander stuff here. ONLY ASYNC-SAFE FUNCTIONS!
}

- (BOOL)application:(__unused UIApplication*) application didFinishLaunchingWithOptions:(__unused NSDictionary*) launchOptions
{
    [KSCrash sharedInstance].onCrash = myCrashHandler;
}
```

**Comment by 74981** [comment]
I have used that but app still terminate. Can you please help me to avoid App termination? like u mentioned earlier dont return from OnCrash but i am not sure from where i can use that. Please help. Just want to check how app termination can be avoided.

**Comment by kstenerud** [comment]
```c
static void myCrashHandler(const KSCrashReportWriter* writer)
{
    for(;;)
    {
        sleep(1000);
    }
}
```
That will stop it from returning, and stop the app from terminating. If that function returns, the app terminates.

But the fact that you didn't already know this tells me that you're playing with dangerous forces you don't understand. Don't do this. It's the path to wailing and gnashing of teeth.

**Comment by 74981** [comment]
Thanks. I was thinking if we could somehow stop termination without hanging app. But in that case app will not return from this state and it freezs. Is there any other way like catch the signal or exception and continue execution of app?
