### ISSUE TITLE
Memory usage during reporting

### ISSUE THREAD

**Issue by bamx23** [kstenerud/KSCrash#263]
As I see the code related to reporting, all crash logs load into memory. Are there any possibilities to load them one-by-one. I remember such methods in previous versions like "give me all IDs" and "give me a report by ID". I could make a PR bringing them back, but maybe there is a better way to achieve such behaviour?

**Comment by bamx23** [comment]
@kstenerud, what do you think?

**Comment by kstenerud** [comment]
Yes, I agree it's a good idea. I just need to find some free time

**Comment by bamx23** [comment]
I've created a PR: #274

**Comment by bamx23** [comment]
PR is merged

**Comment by bamx23** [comment]
@kstenerud could you please make a release with this fixes/improvements? `1.16.0`(because of API changes)
