### ISSUE TITLE
KSCrash cause rpages increase ?

### ISSUE THREAD

**Issue by langyanduan** [kstenerud/KSCrash#278]
I'm developing a PacketProvider on iOS. It is often kill by memory limit. This is jetsameEvent file log the memory issue

    {  
        "uuid" : "14350be0-e8a2-3419-b7fa-42ae204997e5",  
        "states" : [  
            "frontmost"  
        ],  
        "killDelta" : 13593,  
        "lifetimeMax" : 795,  
        "age" : 1001079202730,  
        "purgeable" : 0,  
        "fds" : 200,  
        "genCount" : 0,  
        "coalition" : 633,  
        "rpages" : 960,  
        "reason" : "per-process-limit",  
        "pid" : 4624,  
        "idleDelta" : 4,  
        "name" : "RebornTunnel",  
        "cpuTime" : 1223.5413490000001  
    },  

The rpages is 960 and pageSize is 16k, it exceeded the 15MB limit.

So I used the Allocations and Leaks tool in the Instrument, and it looks like the memory usage is always 6mb for a long time, and there is no memory leak.

Next, I use the activity monitor to track the real memory of the process. And manually triggering jetsam event to obtain the rpages of the process. The result is:
 
---------------------------------------------------------  

Activity Monitor real memory: 8.9MB  

JetsamEvent file:  

    {  
        "uuid" : "45eb176c-a6a2-3d21-a83e-e0a1d906e689",  
        "states" : [  
            "frontmost"  
        ],  
        "lifetimeMax" : 1025,  
        "age" : 752714310856,  
        "purgeable" : 0,  
        "fds" : 100,  
        "coalition" : 633,  
        "rpages" : 761,  
        "pid" : 15273,  
        "idleDelta" : 7,  
        "name" : "RebornTunnel",  
        "cpuTime" : 28.378858999999999  
    },  

---------------------------------------------------------  

Activity Monitor real memory: 7.2MB  

JetsamEvent file:  

    {  
        "uuid" : "45eb176c-a6a2-3d21-a83e-e0a1d906e689",  
        "states" : [  
            "frontmost"  
        ],  
        "lifetimeMax" : 1025,  
        "age" : 824910659065,  
        "purgeable" : 0,  
        "fds" : 200,  
        "coalition" : 633,  
        "rpages" : 846,  
        "pid" : 15273,  
        "idleDelta" : 7,  
        "name" : "RebornTunnel",  
        "cpuTime" : 58.712065000000003  
    },  

---------------------------------------------------------  

Activity Monitor real memory: 7.4MB  

JetsamEvent file:  

    {  
        "uuid" : "45eb176c-a6a2-3d21-a83e-e0a1d906e689",  
        "states" : [  
            "frontmost"  
        ],  
        "lifetimeMax" : 1025,  
        "age" : 862117778147,  
        "purgeable" : 0,  
        "fds" : 200,  
        "coalition" : 633,  
        "rpages" : 873,  
        "pid" : 15273,  
        "idleDelta" : 7,  
        "name" : "RebornTunnel",  
        "cpuTime" : 67.771770000000004  
    },  

---------------------------------------------------------  

Activity Monitor real memory: 7.1MB  

JetsamEvent file:  

    {
        "uuid" : "45eb176c-a6a2-3d21-a83e-e0a1d906e689",
        "states" : [
        "frontmost"
        ],
        "lifetimeMax" : 1025,
        "age" : 976246226116,
        "purgeable" : 0,
        "fds" : 200,
        "coalition" : 633,
        "rpages" : 948,
        "pid" : 15273,
        "idleDelta" : 7,
        "name" : "RebornTunnel",
        "cpuTime" : 90.946804
    }

---------------------------------------------------------  

JetsamEvent kill process

JetsamEvent file:  

    {
        "uuid" : "45eb176c-a6a2-3d21-a83e-e0a1d906e689",
        "states" : [
        "frontmost"
        ],
        "killDelta" : 12297,
        "lifetimeMax" : 1025,
        "age" : 985274557995,
        "purgeable" : 0,
        "fds" : 200,
        "genCount" : 0,
        "coalition" : 633,
        "rpages" : 960,
        "reason" : "per-process-limit",
        "pid" : 15273,
        "idleDelta" : 7,
        "name" : "RebornTunnel",
        "cpuTime" : 91.973054000000005
    }

The rpages is always increase, but the real memory is not. These tests were performed on the iPhoneX. 

This has been bothering me for a long time. I tested various conditions that might cause the problem, and it was finally found that there would be no such problem without the introduction of KSCrash.

**Comment by karlvr** [comment]
@langyanduan this is interesting; I am also shipping a packet tunnel provider. I haven't noticed the rpages, but I am currently tracking a memory limit issue over time, so thanks for the heads up on this. I actually haven't managed to get KSCrash to catch crashes in my packet tunnel provider (#279), have you?

**Comment by langyanduan** [comment]
KSCrash is work well for my provider, I change the crash directory to app group.
