### ISSUE TITLE
If we integrate KSCrash, will App Store reject our app or not?

### ISSUE THREAD

**Issue by ziiip** [kstenerud/KSCrash#299]
As KSCrash using dlsym() function, will App Store reject the code?
Any app with KSCrash are still selling in App Store?

**Comment by mickeyl** [comment]
While it's always a bit of hit-and-miss with Apple Review, I have several apps in the store that include KSCrash. `dlsym()` usage per se is not a problem.

**Comment by ziiip** [comment]
Thanks very much. @mickeyl
