### ISSUE TITLE
Information Display of Third Party Collapse

### ISSUE THREAD

**Issue by woniurensheng** [kstenerud/KSCrash#300]
![2018-11-29 11 40 36](https://user-images.githubusercontent.com/32923446/49197942-e757c600-f3cb-11e8-8d7f-72534c0bf4b5.png)

but  It should be like this：

![2018-11-29 11 44 47](https://user-images.githubusercontent.com/32923446/49198125-b7f58900-f3cc-11e8-8d8b-cf307264e52b.png)

**Comment by VladimirKBM** [comment]
11 days ago
