### ISSUE TITLE
pod can not install latest version

### ISSUE THREAD

**Issue by irresponser** [kstenerud/KSCrash#320]
pod can not install latest version(v1.15.19). My cocoapods version is 1.6.1.  I wondering if the latest version hasn't released successfully.

**Comment by bamx23** [comment]
Could you provide an error message from CocoaPods logs?

**Comment by irresponser** [comment]
the error message : 
[!] CocoaPods could not find compatible versions for pod "KSCrash":
  In Podfile:
    KSCrash (~> 1.15.19)

None of your spec sources contain a spec satisfying the dependency: `KSCrash (~> 1.15.19)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

I exec pod search KSCrash, the result come out like:

-> KSCrash (1.15.18)
   The Ultimate iOS Crash Reporter
   pod 'KSCrash', '~> 1.15.18'
   - Homepage: https://github.com/kstenerud/KSCrash
   - Source:   https://github.com/kstenerud/KSCrash.git
   - Versions: 1.15.18, 1.15.17, 1.15.16, 1.15.12, 1.15.11, 1.15.10, 1.15.9, 1.15.8, 1.15.7,
   1.15.6, 1.15.5, 1.15.4, 1.15.3, 1.15.2, 1.15.1, 1.15.0, 1.14.2, 1.14.0, 1.13.6, 1.13.5,
   1.13.4, 1.13.3, 1.13.2, 1.13.1, 1.13.0, 1.12.2, 1.12.0, 1.11.2, 1.11.1, 1.11.0, 1.10.3,
   1.10.1, 1.10.0, 1.9.5, 1.9.3, 1.9.2, 1.9.1, 1.8.13, 1.8.7, 1.8.5, 1.8.3, 1.8.2, 1.8.0,
   1.7.0, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0, 1.5.11, 1.5.10, 1.5.9, 1.5.8, 1.5.7, 1.5.6,
   1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.3.4, 1.3.3,
   1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.3, 1.0.1, 1.0.0, 0.0.9, 0.0.8, 0.0.7,
   0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1 [master repo]
   - Subspecs:
     - KSCrash/Recording (1.15.18)
     - KSCrash/Recording/Tools (1.15.18)
     - KSCrash/Reporting (1.15.18)
     - KSCrash/Reporting/Filters (1.15.18)
     - KSCrash/Reporting/Filters/Base (1.15.18)
     - KSCrash/Reporting/Filters/Alert (1.15.18)
     - KSCrash/Reporting/Filters/AppleFmt (1.15.18)
     - KSCrash/Reporting/Filters/Basic (1.15.18)
     - KSCrash/Reporting/Filters/Stringify (1.15.18)
     - KSCrash/Reporting/Filters/GZip (1.15.18)
     - KSCrash/Reporting/Filters/JSON (1.15.18)
     - KSCrash/Reporting/Filters/Sets (1.15.18)
     - KSCrash/Reporting/Filters/Tools (1.15.18)
     - KSCrash/Reporting/Tools (1.15.18)
     - KSCrash/Reporting/MessageUI (1.15.18)
     - KSCrash/Reporting/Sinks (1.15.18)
     - KSCrash/Installations (1.15.18)
     - KSCrash/Core (1.15.18)

**Comment by irresponser** [comment]
the latest version hasn't released successfully!

**Comment by ZhiyuWong** [comment]
It seems @kstenerud forgot push KSCrash.podspec into spec repository of CocoaPods.

**Comment by ZhiyuWong** [comment]
> It seems @kstenerud forgot push KSCrash.podspec into spec repository of CocoaPods.

I have tried to push it, but I don't have permission to do that.

**Comment by bamx23** [comment]
I've pushed 1.15.19

**Comment by ZhiyuWong** [comment]
solved
