### ISSUE TITLE
Architecture.md

### ISSUE THREAD

**Issue by CoderLeonidas** [kstenerud/KSCrash#329]
Excuse me, where is the Architecture.md? I just could't find it!

**Comment by kstenerud** [comment]
It's in the top-level directory: https://github.com/kstenerud/KSCrash/blob/master/Architecture.md

**Comment by CoderLeonidas** [comment]
> It's in the top-level directory: https://github.com/kstenerud/KSCrash/blob/master/Architecture.md

Yeah, I got it, Thank you!! /:strong

**Comment by ZhiyuWong** [comment]
solved.
