### ISSUE TITLE
I got a crash report full of null

### ISSUE THREAD

**Issue by SnailLife** [kstenerud/KSCrash#348]
![null_crash](https://user-images.githubusercontent.com/32923446/63209015-29699900-c10e-11e9-8ae5-7abd1a5f89a7.png)

**Comment by ZhiyuWong** [comment]
Please attach a full crash report for more detail.

**Comment by Xcoder1011** [comment]
You set the monitoring must contain at least KSCrashMonitorTypeSystem and KSCrashMonitorTypeApplicationState.
