### ISSUE TITLE
Conflict with AMapLocationKit(高德定位)

### ISSUE THREAD

**Issue by luzsyn** [kstenerud/KSCrash#397]
In my project, import AMapLocationKit to location.

Codes:
NSArray* array = [[NSArray alloc]initWithObjects:@1, @2, @3, nil];
NSNumber* number = [array objectAtIndex:4];
NSLog(@"number = %@", number);

When I init a class of AMapLocationManager instance , like:
self.locationManager = [[AMapLocationManager alloc] init];
[self.locationManager startUpdatingLocation];

**The crash report is :**

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x00000000 at 0x0000000181d9c11c
Crashed Thread:  0

Thread 0 Crashed:
0   libsystem_kernel.dylib          0x0000000181d9c11c 0x181d80000 + 114972 (__pthread_kill + 8)
1   libsystem_c.dylib               0x0000000181d0ddac 0x181cac000 + 400812 (abort + 140)
2   libc++abi.dylib                 0x00000001818413f4 0x181840000 + 5108 (<redacted> + 132)
3   libc++abi.dylib                 0x000000018185de98 0x181840000 + 122520 (<redacted> + 304)
4   libobjc.A.dylib                 0x0000000181868248 0x181860000 + 33352 (<redacted> + 124)
5   Simple-Example                  0x00000001000525e8 0x100040000 + 75240 (CPPExceptionTerminate() + 228)
6   libc++abi.dylib                 0x000000018185af44 0x181840000 + 110404 (<redacted> + 16)
7   libc++abi.dylib                 0x000000018185ab10 0x181840000 + 109328 (__cxa_rethrow + 144)
8   libobjc.A.dylib                 0x0000000181868120 0x181860000 + 33056 (objc_exception_rethrow + 44)
9   CoreFoundation                  0x00000001820e0cf8 0x1820d8000 + 36088 (CFRunLoopRunSpecific + 552)
10  GraphicsServices                0x00000001839c8088 0x1839bc000 + 49288 (GSEventRunModal + 180)
11  UIKit                           0x00000001873ca088 0x18734c000 + 516232 (UIApplicationMain + 204)
12  Simple-Example                  0x0000000100046760 0x100040000 + 26464 (main + 88)
13  libdyld.dylib                   0x0000000181c7e8b8 0x181c7c000 + 10424 (<redacted> + 4)

=====================================

When I not use the AMapLocationManager, KSCrash works right!

**The crash report is:** 
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x00000000 at 0x0000000000000000
Crashed Thread:  0

Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 4 beyond bounds [0 .. 2]'

Thread 0 Crashed:
0   CoreFoundation                  0x0000000182202db0 0x1820d8000 + 1224112 (<redacted> + 124)
1   libobjc.A.dylib                 0x0000000181867f80 0x181860000 + 32640 (objc_exception_throw + 56)
2   CoreFoundation                  0x00000001820e3098 0x1820d8000 + 45208 (<redacted> + 196)
3   Simple-Example                  0x00000001000e1c70 0x1000dc000 + 23664 (-[ViewController onCrash:] + 212)
4   UIKit                           0x0000000187398be8 0x18734c000 + 314344 (<redacted> + 100)
5   UIKit                           0x0000000187398b64 0x18734c000 + 314212 (<redacted> + 80)
6   UIKit                           0x0000000187380870 0x18734c000 + 215152 (<redacted> + 436)
7   UIKit                           0x0000000187398454 0x18734c000 + 312404 (<redacted> + 572)
8   UIKit                           0x0000000187398084 0x18734c000 + 311428 (<redacted> + 804)
9   UIKit                           0x0000000187390c20 0x18734c000 + 281632 (<redacted> + 784)
10  UIKit                           0x000000018736104c 0x18734c000 + 86092 (<redacted> + 248)
11  UIKit                           0x000000018735f628 0x18734c000 + 79400 (<redacted> + 6568)
12  CoreFoundation                  0x00000001821b909c 0x1820d8000 + 921756 (<redacted> + 24)
13  CoreFoundation                  0x00000001821b8b30 0x1820d8000 + 920368 (<redacted> + 540)
14  CoreFoundation                  0x00000001821b6830 0x1820d8000 + 911408 (<redacted> + 724)
15  CoreFoundation                  0x00000001820e0c50 0x1820d8000 + 35920 (CFRunLoopRunSpecific + 384)
16  GraphicsServices                0x00000001839c8088 0x1839bc000 + 49288 (GSEventRunModal + 180)
17  UIKit                           0x00000001873ca088 0x18734c000 + 516232 (UIApplicationMain + 204)
18  Simple-Example                  0x00000001000e2760 0x1000dc000 + 26464 (main + 88)
19  libdyld.dylib                   0x0000000181c7e8b8 0x181c7c000 + 10424 (<redacted> + 4)

It is very very strange，and it happens in your demo .

So who can help me?

**Comment by Kam-To** [comment]
Cloud you share your demo to reproducing this issue?

I'm currently dealing with similar problem but there is no way for me to reproducing it.

**Comment by luzsyn** [comment]
> Cloud you share your demo to reproducing this issue?
> 
> I'm currently dealing with similar problem but there is no way for me to reproducing it.

Amap SDK`s problem，whose sad solved in newest SDK，but we did not test, because we change KSCrash to others.

Demo:
链接: https://pan.baidu.com/s/1COuIZYeWVFalszq8ctq25A  密码: hq4m
