### ISSUE TITLE
KSCrash crash while handling NSExceptions

### ISSUE THREAD

**Issue by yvasileuski** [kstenerud/KSCrash#40]
Thread 0 Crashed:
0   ???                               0000000000 0 + 0
1   CoreFoundation                    0x30435184 __handleUncaughtException + 580
2   libobjc.A.dylib                   0x3a791926 _objc_terminate() + 174
3   Dummy                             0x00078414 CPPExceptionTerminate() (KSCrashSentry_CPPException.mm:199)
4   libc++abi.dylib                   0x3a1571b2 std::__terminate(void (*)()) + 78
5   libc++abi.dylib                   0x3a156d16 __cxa_rethrow + 102
6   libobjc.A.dylib                   0x3a79180e objc_exception_rethrow + 42
7   CoreFoundation                    0x303684e6 CFRunLoopRunSpecific + 642
8   CoreFoundation                    0x30368252 CFRunLoopRunInMode + 106
9   GraphicsServices                  0x350a22ea GSEventRunModal + 138
10  UIKit                             0x32c1d844 UIApplicationMain + 1136
11  Dummy                             0x00054d08 main (main.m:16)
12  libdyld.dylib                     0x3ac8aab6 start + 2

**Comment by woniurensheng** [comment]
I meet one crash while I used KSCrsh to my library!
![20190124142802882](https://user-images.githubusercontent.com/32923446/51659079-82dc7000-1fe4-11e9-8daf-7aa1ee578840.png)
 
how to fix it?
