### ISSUE TITLE
Most messages are null when recrash happens

### ISSUE THREAD

**Issue by Nightmare1995** [kstenerud/KSCrash#410]
Hello,
I received a lot of crash reports as is shown. Most of these reports are full of null, while lacking crash stack. I have no idea to find out the problem.
![impicture_20210602_102546](https://user-images.githubusercontent.com/26626372/120415278-da95fd80-c38d-11eb-9542-cd501e1447a3.png)

I noticed there is a fix about recrash from shino-996. The version of KSCrash I use if 1.15.9. Perhaps I should upgrade my KSCrash.
![image](https://user-images.githubusercontent.com/26626372/120417739-edaacc80-c391-11eb-87f3-e310ae337f0f.png)

Any suggestion? Thanks.

**Comment by nickh-apadmi** [comment]
Could you check if you can reproduce the issue with the latest version (1.15.25)?

**Comment by Nightmare1995** [comment]
@nickh-apadmi Thank you. Unfortunately, these reports are collected from the users of my app and I don't know how to reproduce the issue.

**Comment by Nightmare1995** [comment]
@nickh-apadmi I upgrade my KSCrash to 1.15.25 for a few months and this issue no longer appears.

**Comment by whde** [comment]
1.15.25 also appears
