### ISSUE TITLE
Any reason why two KSCrash handlers are created?

### ISSUE THREAD

**Issue by hiraditya** [kstenerud/KSCrash#428]
There are two handlers
```
static const char* kThreadPrimary = "KSCrash Exception Handler (Primary)";
static const char* kThreadSecondary = "KSCrash Exception Handler (Secondary)";
```

https://github.com/kstenerud/KSCrash/blob/master/Source/KSCrash/Recording/Monitors/KSCrashMonitor_MachException.c#L50

Is it possible to have only one. This will reduce KSCrash overhead IMO.

**Comment by Rui4u** [comment]
pull request `update: fix getdata() mask #429` fix it
