### ISSUE TITLE
KSCrash cannot be used as a podspec dependency starting from Xcode 14.3

### ISSUE THREAD

**Issue by matux** [kstenerud/KSCrash#443]
Starting from Xcode 14.3, support for iOS <11 has been dropped. When creating a `podspec` that requires `KSCrash` as a dependency, `pod lint` as well as `pod trunk push` fail to successfully link the pod project since `KSCrash` minimum deployment requirements are under what Xcode 14.3 supports.

This can be fixed  simply by changing `KSCrash.podspec` minimum deployment versions for each OS to the new lowest supported by Xcode 14.3 and then republishing the library to the Cocoapods registry.

I can make this change myself and send a PR, but I won't be able to publish to Cocoapods.

You can find more details in here:
https://github.com/CocoaPods/CocoaPods/issues/11839

This is the error in question:
```
ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bamx23** [comment]
Thanks @matux for flagging this issue and sorry for a delay. Fixed in 1.16.0
