### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by MrJokerBoy** [kstenerud/KSCrash#453]
When KSCrash is introduced through pod install, the error Command PhaseScriptExecution failed with a nonzero exit code appears.

**Comment by GLinnik21** [comment]
Hey! The issue with `Command PhaseScriptExecution failed with a nonzero exit code` might not necessarily be related to KSCrash. To help better diagnose the problem, could you share some more details from your build log where the error occurs? If this is still an issue for you, please add the logs and reopen the issue. I'll mark it as closed for now until we get more details. Thanks!
