### ISSUE TITLE
Privacy manifests for KSCrash 

### ISSUE THREAD

**Issue by zziazm** [kstenerud/KSCrash#456]
Apple need  third-party SDKs to provide privacy manifests，Otherwise, it may not pass the review for app store.
Does kscrash provide a privacy manifests?

**Comment by giobass** [comment]
+1

**Comment by danielepantaleone** [comment]
+1

**Comment by GLinnik21** [comment]
Feel free to discuss it here #457.

**Comment by bamx23** [comment]
#457 has been merged and the corresponding release is out: 1.17.0.
Thanks @GLinnik21 for contribution!
