### ISSUE TITLE
Targets names are not compliant with UTI

### ISSUE THREAD

**Issue by kapitoshka438** [kstenerud/KSCrash#458]
In an ideal world, targets names have to be [Uniform Type Identifiers](https://developer.apple.com/documentation/uniformtypeidentifiers/defining_file_and_data_types_for_your_app).
Although the classic approach to add SPM dependencies through Xcode works fine with KSCrash by replacing slash symbol (`/`) with underscore (`_`) but it makes it tough to build an **xcframework**.
KSCrash and also those who import it as a transitive dependency don't work with Tuist - the most popular tool for generating Xcode projects and managing and caching SPM dependencies.
Do you mind removing slashes from targets names in `Package.swift`.
[Firebase](https://github.com/firebase/firebase-ios-sdk/blob/main/Package.swift) is a great example.

**Comment by TopIvanAbramov** [comment]
@GLinnik21 actually the problem wasnt solved, we still get similar error due to stange naming: use of "/" in names

Can you fix it?

**Comment by GLinnik21** [comment]
Hi! 
The development focus is currently on the branch [release-2.0](https://github.com/kstenerud/KSCrash/tree/release-2.0), and no stable release has been made with the necessary changes. You might consider using this branch as a dependency temporarily. However, be cautious, as it may include some breaking changes and could be unstable. It might be worth waiting for a more stable release if your project requires high reliability.

**Comment by TopIvanAbramov** [comment]
Thank you! Do you have any specific dates for the stable release?

**Comment by GLinnik21** [comment]
This is an open-source project developed in the contributors' free time, so it's a bit tough to pin down exact timelines for stable releases. We could potentially roll out a beta version for SPM, but as I mentioned earlier, it might be highly unstable and it would also lack the required privacy report. If you're keen to see the changes sooner, you could definitely speed things up by contributing a PR with the necessary fixes. That would be super helpful!
