### ISSUE TITLE
Xcode15，Swift set C++ and Objective-C Interoperability --> C++/Object-C++，Unable to catch exception

### ISSUE THREAD

**Issue by huakucha** [kstenerud/KSCrash#461]
<img width="552" alt="image" src="https://github.com/kstenerud/KSCrash/assets/5646613/68949dc0-e1cc-485a-8d7a-d46221a84f5f">

 C++/Object-C++, Unable to catch exception
 C/Object-C, Can catch exceptions

**Comment by GLinnik21** [comment]
Duplicate #460
