### ISSUE TITLE
Died at ./symbolicatecrash line 1207

### ISSUE THREAD

**Issue by 1025550** [kstenerud/KSCrash#471]
./symbolicatecrash ./crash_1715049849108.txt  > symbol.crash
atos cannot load symbols for the file /Users/wangrong/Library/Developer/Xcode/iOS DeviceSupport/iPhone14,7 17.4.1 (21E236)/Symbols/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore for architecture arm64.
Died at ./symbolicatecrash line 1207 我只用iPhone14 iOS17.4.1 他就报这个错误，生成了一个空的文件，我的手机系统生成的这个文件是arm64e的，请问我该怎么处理啊

**Comment by GLinnik21** [comment]
Hey @1025550,

From your description, it isn’t clear how this crash relates to the KSCrash library. I'm going to close this issue for now. If you believe KSCrash is involved and can provide more details like reproduction steps, relevant samples, or related files and crash logs, please feel free to reopen the issue with that info.

Thanks!
