### ISSUE TITLE
Do not compile with Xcode 16.

### ISSUE THREAD

**Issue by c128128** [kstenerud/KSCrash#498]
<img width="580" alt="Screenshot 2024-06-11 at 14 43 48" src="https://github.com/kstenerud/KSCrash/assets/69604865/bed21db9-e88a-463e-b032-78ce2a4fc3de">

Please merge this PR #497

**Comment by GLinnik21** [comment]
Here is the fix for 1.x version https://github.com/kstenerud/KSCrash/commit/1756e48e29244a1f46bdc4b630abba4a532e5a7f
