### ISSUE TITLE
Workspaces can't find source files

### ISSUE THREAD

**Issue by armcknight** [kstenerud/KSCrash#500]
There are a couple workspaces like iOS.xcworkspace etc that have broken paths to source files after what looks like several reorganizations of the file structure:
<img width="1512" alt="image" src="https://github.com/kstenerud/KSCrash/assets/3241469/2c3315fd-5382-4ef2-b8b2-4946436f09e1">

It looks like opening from the Package.swift is the preferred way to write code here now; either those old xcworkspaces should be removed, or have the broken paths fixed.

**Comment by GLinnik21** [comment]
Duplicates #495

**Comment by GLinnik21** [comment]
I'll clean up the project soon and remove the old project files.

**Comment by bamx23** [comment]
@armcknight does it break the KSCrash as a library? As I can imagine it can break Carthage, but I don't think we're supporting it as a way to districbute KSCrash.

And yes, we are planning to rework the samples setup and cleanup things.
