### ISSUE TITLE
Is there a problem with multi-threaded calling ksmc_SuspendeneEnvironment()

### ISSUE THREAD

**Issue by zhouyantongiosDev** [kstenerud/KSCrash#539]
I have a thread A and a thread B, both threads are running continuously and will call ksmc_SuspendeneEnvironment() to suspend and capture the stack. I am worried about deadlock and other abnormal issues

**Comment by GLinnik21** [comment]
Hi!
To better understand and assist with your issue, could you please provide more specific information. Have you actually encountered any deadlocks or abnormal issues when calling `ksmc_SuspendeneEnvironment()` from multiple threads? If so, can you share details like stack traces or error messages?

**Comment by zhouyantongiosDev** [comment]
> messages

I didn't encounter it, I was just worried about potential issues during the development phase and came to inquire if there might be any hanging problems. I'm not sure about the underlying principles

**Comment by GLinnik21** [comment]
As the maintainer of KSCrash, I can assure you that neither we nor our many users have reported any recent issues related to multi-threaded calls to `ksmc_suspendEnvironment()`. 

Theoretically, the only scenario where problems might arise is if there's synchronization within the system Mach libraries used for thread suspension, and a crash occurs within those system libraries. This could potentially be an issue if these libraries are not async-safe or re-entrant-safe.

To be absolutely certain about the underlying implementation and potential edge cases, you can explore the open-source Mach kernel code. This would give you direct insight into how these low-level operations are handled and confirm their thread-safety and re-entrancy properties.

**Comment by zhouyantongiosDev** [comment]
> As the maintainer of KSCrash, I can assure you that neither we nor our many users have reported any recent issues related to multi-threaded calls to `ksmc_suspendEnvironment()`.
> 
> Theoretically, the only scenario where problems might arise is if there's synchronization within the system Mach libraries used for thread suspension, and a crash occurs within those system libraries. This could potentially be an issue if these libraries are not async-safe or re-entrant-safe.
> 
> To be absolutely certain about the underlying implementation and potential edge cases, you can explore the open-source Mach kernel code. This would give you direct insight into how these low-level operations are handled and confirm their thread-safety and re-entrancy properties.

Do we need to add a lock? For example:

`static pthread_mutex_t g_mutex = PTHREAD_MUTEX_INITIALIZER;

void ksmc_suspendEnvironment() {
#if KSCRASH_HAS_THREADS_API
    KSLOG_DEBUG("Suspending environment.");
    kern_return_t kr;
    const task_t thisTask = mach_task_self();
    const thread_t thisThread = (thread_t)ksthread_self();

    if (g_suspendedThreads != NULL) {
        return;
    }

    pthread_mutex_lock(&g_mutex);

    if ((kr = task_threads(thisTask, &g_suspendedThreads, &g_suspendedThreadsCount)) != KERN_SUCCESS) {
        KSLOG_ERROR("task_threads: %s", mach_error_string(kr));
        pthread_mutex_unlock(&g_mutex);
        return;
    }

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        thread_t thread = g_suspendedThreads[i];
        if (thread != thisThread && !isThreadInList(thread, g_reservedThreads, g_reservedThreadsCount)) {
            if ((kr = thread_suspend(thread)) != KERN_SUCCESS) {
                // Record the error and keep going.
                KSLOG_ERROR("thread_suspend (%08x): %s", thread, mach_error_string(kr));
            }
        }
    }

    pthread_mutex_unlock(&g_mutex);

    KSLOG_DEBUG("Suspend complete.");
#endif
}

void ksmc_resumeEnvironment() {
#if KSCRASH_HAS_THREADS_API
    KSLOG_DEBUG("Resuming environment.");
    kern_return_t kr;
    const task_t thisTask = mach_task_self();
    const thread_t thisThread = (thread_t)ksthread_self();

    if (g_suspendedThreads == NULL || g_suspendedThreadsCount == 0) {
        KSLOG_ERROR("we should call ksmc_suspendEnvironment() first");
        return;
    }

    pthread_mutex_lock(&g_mutex);

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        thread_t thread = g_suspendedThreads[i];
        if (thread != thisThread && !isThreadInList(thread, g_reservedThreads, g_reservedThreadsCount)) {
            if ((kr = thread_resume(thread)) != KERN_SUCCESS) {
                // Record the error and keep going.
                KSLOG_ERROR("thread_resume (%08x): %s", thread, mach_error_string(kr));
            }
        }
    }

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        mach_port_deallocate(thisTask, g_suspendedThreads[i]);
    }
    vm_deallocate(thisTask, (vm_address_t)g_suspendedThreads, sizeof(thread_t) * g_suspendedThreadsCount);
    g_suspendedThreads = NULL;
    g_suspendedThreadsCount = 0;

    pthread_mutex_unlock(&g_mutex);

    KSLOG_DEBUG("Resume complete.");
#endif
}
`

**Comment by zhouyantongiosDev** [comment]
> As the maintainer of KSCrash, I can assure you that neither we nor our many users have reported any recent issues related to multi-threaded calls to `ksmc_suspendEnvironment()`.
> 
> Theoretically, the only scenario where problems might arise is if there's synchronization within the system Mach libraries used for thread suspension, and a crash occurs within those system libraries. This could potentially be an issue if these libraries are not async-safe or re-entrant-safe.
> 
> To be absolutely certain about the underlying implementation and potential edge cases, you can explore the open-source Mach kernel code. This would give you direct insight into how these low-level operations are handled and confirm their thread-safety and re-entrancy properties.

Do we need to add a lock? For example:
`
static pthread_mutex_t g_mutex = PTHREAD_MUTEX_INITIALIZER;
void ksmc_resumeEnvironment() {
#if KSCRASH_HAS_THREADS_API
    KSLOG_DEBUG("Resuming environment.");
    kern_return_t kr;
    const task_t thisTask = mach_task_self();
    const thread_t thisThread = (thread_t)ksthread_self();

    if (g_suspendedThreads == NULL || g_suspendedThreadsCount == 0) {
        KSLOG_ERROR("we should call ksmc_suspendEnvironment() first");
        return;
    }

    pthread_mutex_lock(&g_mutex);

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        thread_t thread = g_suspendedThreads[i];
        if (thread != thisThread && !isThreadInList(thread, g_reservedThreads, g_reservedThreadsCount)) {
            if ((kr = thread_resume(thread)) != KERN_SUCCESS) {
                // Record the error and keep going.
                KSLOG_ERROR("thread_resume (%08x): %s", thread, mach_error_string(kr));
            }
        }
    }

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        mach_port_deallocate(thisTask, g_suspendedThreads[i]);
    }
    vm_deallocate(thisTask, (vm_address_t)g_suspendedThreads, sizeof(thread_t) * g_suspendedThreadsCount);
    g_suspendedThreads = NULL;
    g_suspendedThreadsCount = 0;

    pthread_mutex_unlock(&g_mutex);

    KSLOG_DEBUG("Resume complete.");
#endif
}
`

**Comment by zhouyantongiosDev** [comment]
Do we need to add a lock? For example:

static pthread_mutex_t g_mutex = PTHREAD_MUTEX_INITIALIZER;

void ksmc_suspendEnvironment() {
#if KSCRASH_HAS_THREADS_API
    KSLOG_DEBUG("Suspending environment.");
    kern_return_t kr;
    const task_t thisTask = mach_task_self();
    const thread_t thisThread = (thread_t)ksthread_self();

    if (g_suspendedThreads != NULL) {
        return;
    }

    pthread_mutex_lock(&g_mutex);

    if ((kr = task_threads(thisTask, &g_suspendedThreads, &g_suspendedThreadsCount)) != KERN_SUCCESS) {
        KSLOG_ERROR("task_threads: %s", mach_error_string(kr));
        pthread_mutex_unlock(&g_mutex);
        return;
    }

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        thread_t thread = g_suspendedThreads[i];
        if (thread != thisThread && !isThreadInList(thread, g_reservedThreads, g_reservedThreadsCount)) {
            if ((kr = thread_suspend(thread)) != KERN_SUCCESS) {
                // Record the error and keep going.
                KSLOG_ERROR("thread_suspend (%08x): %s", thread, mach_error_string(kr));
            }
        }
    }

    pthread_mutex_unlock(&g_mutex);

    KSLOG_DEBUG("Suspend complete.");
#endif
}

void ksmc_resumeEnvironment() {
#if KSCRASH_HAS_THREADS_API
    KSLOG_DEBUG("Resuming environment.");
    kern_return_t kr;
    const task_t thisTask = mach_task_self();
    const thread_t thisThread = (thread_t)ksthread_self();

    if (g_suspendedThreads == NULL || g_suspendedThreadsCount == 0) {
        KSLOG_ERROR("we should call ksmc_suspendEnvironment() first");
        return;
    }

    pthread_mutex_lock(&g_mutex);

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        thread_t thread = g_suspendedThreads[i];
        if (thread != thisThread && !isThreadInList(thread, g_reservedThreads, g_reservedThreadsCount)) {
            if ((kr = thread_resume(thread)) != KERN_SUCCESS) {
                // Record the error and keep going.
                KSLOG_ERROR("thread_resume (%08x): %s", thread, mach_error_string(kr));
            }
        }
    }

    for (mach_msg_type_number_t i = 0; i < g_suspendedThreadsCount; i++) {
        mach_port_deallocate(thisTask, g_suspendedThreads[i]);
    }
    vm_deallocate(thisTask, (vm_address_t)g_suspendedThreads, sizeof(thread_t) * g_suspendedThreadsCount);
    g_suspendedThreads = NULL;
    g_suspendedThreadsCount = 0;

    pthread_mutex_unlock(&g_mutex);

    KSLOG_DEBUG("Resume complete.");
#endif
}

**Comment by GLinnik21** [comment]
Thank you for your suggestion. While I appreciate the intent, introducing global variables and locks could potentially create new risks and complexity. Are you interested in creating a Pull Request to improve `ksmc_suspendEnvironment`, or were you just asking about potential improvements?

**Comment by zhouyantongiosDev** [comment]
> Thank you for your suggestion. While I appreciate the intent, introducing global variables and locks could potentially create new risks and complexity. Are you interested in creating a Pull Request to improve `ksmc_suspendEnvironment`, or were you just asking about potential improvements?

Just inquiring about potential improvements
