### ISSUE TITLE
CWE-328: Use of Weak Hash CC_SHA1 in KSCrashMonitor_System.m

### ISSUE THREAD

**Issue by bingosoft** [kstenerud/KSCrash#543]
Hello! We are using **KSCrash** library in our app and have faced with security issue after App Penetration Testing (APT):

**[CWE-328: Use of Weak Hash](https://cwe.mitre.org/data/definitions/328.html)**

After some investigation we noticed that `KSCrash` uses weak `CC_SHA1` hashing algorithm in [KSCrashRecording/Monitors/KSCrashMonitor_System.m:365](https://github.com/kstenerud/KSCrash/blob/master/Sources/KSCrashRecording/Monitors/KSCrashMonitor_System.m#L365) 

This leads that our binary also imports this symbol when execute `otool -Iv AppBinary | grep CC_SHA1`, and as result to security issues in reports. 

Is it possible to use more stronger hash function, e.g. `SHA256` in your library?

Thanks!

**Comment by GLinnik21** [comment]
Hi!
Thank you for bringing this to our attention!
Could you please let us know if you have encountered any issues with the Apple App Store review process due to this? Additionally, could you clarify what specific security threats are introduced by this hash usage since it is primarily for device identification in crash reports?

**Comment by GLinnik21** [comment]
Technically, it's not a problem, but some users may rely on this hash. @bamx23, what do you think?

**Comment by bingosoft** [comment]
> Could you please let us know if you have encountered any issues with the Apple App Store review process due to this?

It's not regarding AppStore review process. Some teams have so named *App Penetration Testing* before promoting to AppStore, where a third-party team tries to find vulnerabilities and insecure API usage during a binary analysis. We are unable to show our source code to them and say, OK guys, here you can see that it was not us, this `SHA1` is used in third-party framework for hashing device id. And even in this case probably it will be a point for a security concern. They just see, that our binary imports this function and raise a security concern. Basically fixing the usage of `SHA1` to `SHA256` will also help to another teams who uses `KSCrash` and have **APT** before publishing to AppStore.

> Additionally, could you clarify what specific security threats

Using of `SHA256` is more reliable hashing algorithm, almost eliminates the possibility of collisions. A device id will become much better and unique :)

>**SHA1**: Secure Hash Algorithm 1 (SHA1) was designed by the NSA. Like MD5, SHA1 is vulnerable to collision attacks. By 2005 SHA1 was considered insecure, in 2011 the National Institute of Standards and Technology (NIST) formally deprecated it.
>**SHA256**: is a member of the SHA-2 set. the suffix 256 stands for 256 bits which is the length of the hash value produced. SHA-256 is a secure and trusted industry standard with near impossible chance of collisions (2^256).

https://docs.ostorlab.co/kb/WEAK_HASHING_ALGO/index.html

**Comment by GLinnik21** [comment]
Thank you for your detailed follow-up. After careful consideration, we've concluded that changing the hashing algorithm from SHA1 to SHA256 in this specific case could potentially cause more issues than it would solve. Here's our reasoning:

1. Usage Context: The SHA1 hash in KSCrash is used solely for device identification in crash reports, not for any security-critical functionality. In this context, the cryptographic weaknesses of SHA1 do not introduce a practical vulnerability.

2. Data Continuity: Changing the hashing algorithm would result in different device identifiers for the same devices. This could break crash report grouping and make it difficult to track issues across app versions.

3. Analytics Impact: The change could disrupt existing crash analytics, potentially obscuring important trends or recurring issues.

4. Minimal Security Benefit: Given the specific use case, switching to SHA256 would not provide a significant security improvement in practice.

Aside from changing to SHA256, do you have any other suggestions or alternatives that could help resolve the security flags in your penetration testing, while maintaining the current functionality of KSCrash?

**Comment by bingosoft** [comment]
Okay, thank you for your expanded and reasonable response. So, I will fork your project, and solve this problem for my specific case. Have a good day!
