### ISSUE TITLE
Xcode升级到16后，iOS18无法编译成功

### ISSUE THREAD

**Issue by dxpbloom** [kstenerud/KSCrash#557]
Xcode版本：
Version 16.0 beta 6 (16A5230g)

iOS18 模拟器

报错信息：
/Users/bloom.d/vip-union-iOS2/Pods/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:66:13: error: no type named 'terminate_handler' in namespace 'std'
   66 | static std::terminate_handler g_originalTerminateHandler;
      |        ~~~~~^
/Users/bloom.d/vip-union-iOS2/Pods/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:219:47: error: no member named 'set_terminate' in namespace 'std'
  219 |             g_originalTerminateHandler = std::set_terminate(CPPExceptionTerminate);
      |                                          ~~~~~^
/Users/bloom.d/vip-union-iOS2/Pods/KSCrash/Source/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:223:18: error: no type named 'set_terminate' in namespace 'std'
  223 |             std::set_terminate(g_originalTerminateHandler);
      |             ~~~~~^
3 errors generated.

<img width="468" alt="image-2024-9-6_18-1-33" src="https://github.com/user-attachments/assets/33797a69-cbb6-4b92-9495-eaf70d6a8907">

**Comment by GLinnik21** [comment]
Hello!
As this community primarily communicates in English, and to ensure we understand your issue correctly, could you kindly rewrite your message in English? This will help ensure that all participants can follow and contribute to the discussion effectively. But for now, I'll close the issue. Thank you!
