### ISSUE TITLE
Crash cannot be captured by the KSCrash SDK（v.1.17.5）

### ISSUE THREAD

**Issue by jub9637999991** [kstenerud/KSCrash#560]
In my project ， I introduced KSCrashSDK, after the initialization, 
I created a crash, but it has not been captured by KSCrash. Seek Assist。

I have try  KSCrash(1.17.1 、1.17.5). These versions all have the same problem. 
My environment is limited and I can only pull up to version 1.17.5 at the moment . I need  help.

`
  pod 'KSCrash', '1.17.5'

`

create crash 
`
- (IBAction)addCrash:(id)sender {
    NSString * str = @(1);
    NSLog(@"%@", str.length);
}

`

init SDK
`
- (KSCrashInstallation*) makeEmailInstallation
{
   NSString* emailAddress = @"tyf9637999991@gmail.com";
   
   KSCrashInstallationEmail* email = [KSCrashInstallationEmail sharedInstance];
   email.recipients = @[emailAddress];
   email.subject = @"Crash Report";
   email.message = @"This is a crash report";
   email.filenameFmt = @"crash-report-%d.txt.gz";
   
   [email addConditionalAlertWithTitle:@"Crash Detected"
                               message:@"The app crashed last time it was launched. Send a crash report?"
                             yesAnswer:@"Sure!"
                              noAnswer:@"No thanks"];
   
   // Uncomment to send Apple style reports instead of JSON.
   [email setReportStyle:KSCrashEmailReportStyleApple useDefaultFilenameFormat:YES];

   return email;
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    KSCrash* handler = [KSCrash sharedInstance];
    
    // Settings in KSCrash.h
    handler.deadlockWatchdogInterval = 8;
    handler.userInfo = @{@"someKey": @"someValue"};
    handler.monitoring = KSCrashMonitorTypeCPPException;

    KSCrashInstallation* installation = [self makeEmailInstallation];
   
    [installation install];
    
    return YES;
}

`

But it always doesn't work.
<img width="1556" alt="截屏2024-09-09 下午4 50 35" src="https://github.com/user-attachments/assets/ec5fc75c-8c4a-4c10-992f-e2463e3d8d25">

**Comment by GLinnik21** [comment]
Hey there! Have you had a chance to try the suggestion from #501?

**Comment by GLinnik21** [comment]
Please reopen the issue if you are still having this problem.
