### ISSUE TITLE
Please Enable Discussions

### ISSUE THREAD

**Issue by mickeyl** [kstenerud/KSCrash#561]
It's amazing to see that this project is alive again. Would you mind enabling GitHub discussions? Perhaps this is a good way to exchange best practices around crash reporting on Apple platforms using KSCrash.

**Comment by GLinnik21** [comment]
Great idea! But I think only @kstenerud is able to activate this feature.

**Comment by GLinnik21** [comment]
> It's amazing to see that this project is alive again. Would you mind enabling GitHub discussions? Perhaps this is a good way to exchange best practices around crash reporting on Apple platforms using KSCrash.

Done! Feel free to open the first topic.
