### ISSUE TITLE
Use of undeclared identifier INT_MAX in KCrash 2.0.0-rc.2

### ISSUE THREAD

**Issue by albertolobohasten** [kstenerud/KSCrash#566]
The file KSCrashMonitor_AppState.h don'tdo the include #include <limits.h>, so sometimes we have an error "Use of undeclared identifier 'INT_MAX'" compiling against Xcode 16 in the KCrash 2.0.0-rc.2 version.

![Captura de pantalla 2024-09-19 a las 10 51 09](https://github.com/user-attachments/assets/bcae6cc5-ffc6-4e7f-9188-d36f3473c6ea)

**Comment by GLinnik21** [comment]
Thanks for reporting. This should be fixed in PR #564, included in 2.0.0-rc.2. Could you share your Podfile.lock to confirm you're using this version?

**Comment by albertolobohasten** [comment]
You have all reason we have the previous version via the Appmetrika SDK. We can close this one and open one issue in the SDK, really thanks!
  - KSCrash/Core (2.0.0-rc.1)
  - KSCrash/Recording (2.0.0-rc.1):
    - KSCrash/RecordingCore
  - KSCrash/RecordingCore (2.0.0-rc.1):
    - KSCrash/Core
