### ISSUE TITLE
build with xcode 16 error:no type named 'terminate_handler' in namespace 'std'

### ISSUE THREAD

**Issue by lishulong199253** [kstenerud/KSCrash#567]
/Users/along/Desktop/companyCode2/GJCrashComponent/GJCrashComponent/Classes/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:66:13: error: no type named 'terminate_handler' in namespace 'std'
   66 | static std::terminate_handler g_originalTerminateHandler;
      |        ~~~~~^
/Users/along/Desktop/companyCode2/GJCrashComponent/GJCrashComponent/Classes/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:219:47: error: no member named 'set_terminate' in namespace 'std'
  219 |             g_originalTerminateHandler = std::set_terminate(CPPExceptionTerminate);
      |                                          ~~~~~^
/Users/along/Desktop/companyCode2/GJCrashComponent/GJCrashComponent/Classes/KSCrash/Recording/Monitors/KSCrashMonitor_CPPException.cpp:223:18: error: no type named 'set_terminate' in namespace 'std'
  223 |             std::set_terminate(g_originalTerminateHandler);
      |             ~~~~~^
3 errors generated.

**Comment by lishulong199253** [comment]
add '#include <exception>' in KSCrashMonitor_CPPException.cpp

**Comment by lichanghong** [comment]
include what？

**Comment by fancymiracle** [comment]
> include what？
#include <exception>
