### ISSUE TITLE
Make sending SIGTERM optional. 

### ISSUE THREAD

**Issue by alexklints** [kstenerud/KSCrash#577]
### Describe the bug

In [issue](https://github.com/kstenerud/KSCrash/pull/472) SIGTERM support has been added, similar to Firebase and Sentry. Firebase and Sentry have disabled their collection by default, as they produce a very large number of false crashes. It would be cool to remove the default SIGTERM collection and make it configurable.

### Steps to reproduce

During normal use.

### KSCrash version

2.0.0

### Operating System

iOS

### OS version

all

**Comment by bamx23** [comment]
Thanks for a bug report. It makes perfect sense to have this feature disabled by default. 
Here's the PR: #578. Once merged we'll make another RC build.
