### ISSUE TITLE
Custom CrashInstallation - initWithRequiredProperties not exposed in public api

### ISSUE THREAD

**Issue by MagdaSzlagor** [kstenerud/KSCrash#581]
### Describe the bug

I'm trying to create a custom CrashInstallation.
When I call init on this class I get a crash with message: KSCrashInstallation does not support init. Subclasses must call initWithRequiredProperties:

### Steps to reproduce

1. call `CrashInstallation()` <- KSCrashInstallation does not support init. Subclasses must call initWithRequiredProperties:
2. try with `CrashInstallation(requiredProperties: [])` <- Argument passed to call that takes no arguments

### KSCrash version

2.0.0-rc.4

### Operating System

iOS

### OS version

iOS 18.0

### Xcode version

16.0

**Comment by bamx23** [comment]
Thanks for this report. I've fixed this issue and also made a required method "sink" visible in public API (release 2.0.0-rc.5). An example of installation subclassing is now a part of the sample.
