### ISSUE TITLE
`deleteBehaviorAfterSendAll` removed and replacement not available via Installations API

### ISSUE THREAD

**Issue by dwrss** [kstenerud/KSCrash#582]
### Describe the issue

`deleteBehaviorAfterSendAll` has been removed from `KSCrashConfiguration`. It looks like, internally, it was replaced with `KSCrashReportStore.reportCleanupPolicy`, but that doesn't seem to be available via the `Installations` api. I'm guessing it was meant to be included on `KSCrashReportStoreConfiguration`.

### Integration method

Swift Package Manager

### Error messages

```shell
None (unless you count the "KSCrashReportStoreConfiguration") compiler error. I just cannot easily configure this property.
```

### KSCrash version

2.0.0-RC.4

### Operating System

iOS

### OS version

18.0.1

### Xcode version

16.0

**Comment by bamx23** [comment]
Thanks for your report. Indeed, this property should be a part of the configuration. Fixed in 2.0.0-rc.5.
