### ISSUE TITLE
适配Xcode16，swift6

### ISSUE THREAD

**Issue by ZClee128** [kstenerud/KSCrash#592]
### Describe the bug

无法集成，提示找不到库

### Steps to reproduce

1. 
2. 
3. 

### KSCrash version

1.17.7

### Operating System

iOS

### OS version

iOS18

### Xcode version

16

### Additional context

解决

**Comment by GLinnik21** [comment]
This issue is being closed because the details are not provided in English and are incomplete. Please feel free to reopen with a complete description in English.
