### ISSUE TITLE
[Question] Readability of crash diagnosis

### ISSUE THREAD

**Issue by angelinec** [kstenerud/KSCrash#597]
### Describe the bug

Is there a way to have better readability of `lastFunctionName/callName` of a crash when it's recorded? Only showing the `<redacted>` infos without the additional substring?

### Steps to reproduce

Trigger a crash to get the diagnosis from crash report

### Crash report or stack trace

**e.g.** Originated at or in a subcall of $s16`<redacted>`18`<redacted>`C10`<redacted>`33_0DCC8E338A8DEB9FDDDEFBFF121F7EC2LL7forTypeyAC0dQ0AELLO_tF

Note: `<redacted>` in the example above are the: `app name`, `file name`, ` function name`

### KSCrash version

2.0.0-rc.8

### Operating System

iOS

### OS version

iOS 17.7.2

### Xcode version

16.1

**Comment by GLinnik21** [comment]
Hi!

I see you're encountering `<redacted>` placeholders in function names, but I'm not sure I fully understand your request. KSCrash itself doesn't add these redactions. Could you:

1. Share a complete crash report example
2. Explain what output format you're expecting to see instead

This will help me better understand how to assist you.

**Comment by angelinec** [comment]
Hey, thanks for getting back! Sorry if it's confusing to you.

1. Originated at or in a subcall of
$s16**App_Name**18**ClassName**C10**FunctionName**33_0DCC8E338A8DEB9 FDDDEFBFF121F7EC2LL7forTypeyAC0dQ0AELLO_tF

I have to omit the app name, class name and function name for confidentiality hence, the `<redacted>` in the original post.

2. I prefer to have it in this format:
Originated at or in a subcall of AppNameClassNameFunctionName

Is there a way to beautify it or remove the remaining substring?

Thanks.

**Comment by GLinnik21** [comment]
Sorry for the delay—looks like my earlier message got lost. If you want to make your crash reports easier to read, try using the `KSCrashDemangleFilter`. It takes care of demangling Swift symbols, so your reports are much clearer. You can add it to your crash report processing pipeline, and it’ll automatically handle demangling during the `sendAllReports` call. If you’re using the Installations API, this module is already enabled by default.
