### ISSUE TITLE
Crashprobe Benchmark

### ISSUE THREAD

**Issue by mackoj** [kstenerud/KSCrash#68]
Hi,

What's do you think of this benchmark for crash framework ?
What are the result of your framework ? Will you contribute to it ?

http://hockeyapp.net/blog/2014/05/23/presenting-crashprobe.html

Cheers,

**Comment by kattrali** [comment]
As an update, KSCrash now passes the corrupt malloc test. The need to copy the `lr` heuristic remains the same if you want comparable results.

**Comment by torarnv** [comment]
What's the status of this nowadays? Thanks! 😄 

Also, is there any collaboration/overlap between the KSCrash and PLCrashReporter codebases?

**Comment by kstenerud** [comment]
Bugsnag uses KSCrash under the hood, so that's basically where KSCrash stands atm.

KSCrash and PLCrashReporter are completely separate. We steal from each other but don't collaborate otherwise. Competition breeds innovation.
