### ISSUE TITLE
Push version 0.0.4 to CocoaPods specs

### ISSUE THREAD

**Issue by BamX** [kstenerud/KSCrash#91]
Release 0.0.4 hasn't been pushed to CocoaPods central specs repository.
@kstenerud, please, could you do it? Is there any problem with this step?

**Comment by BamX** [comment]
I've solved that problem by myself. @kstenerud, please, tell me email of your CocoaPods trunk account, I'll provide you owner rights as you are an actual owner of the library.

**Comment by kstenerud** [comment]
It's my username at gmail.

Odd... I was sure that my cocoapods push had been successful.

**Comment by BamX** [comment]
It's done.
