### ISSUE TITLE
iOS 9 processName unavailable

### ISSUE THREAD

**Issue by elfenlaid** [kstenerud/KSCrash#94]
Hi there :)
Due to iOS 9 privacy policy changes `+ (NSString*) processName:(int) pid` is not longer available.
You can see this log statement in debug:

```
ERROR: KSSysCtl.c (228): _Bool kssysctl_getProcessInfo(const int, struct kinfo_proc *const): Could not get the name for process 326: Operation not permitted

```

Setup: Xcode Version 7.0 beta 3 / OS Yosemiti 10.10.3

**Comment by pavm035** [comment]
Hi,
Any update on this?

**Comment by yvasileuski** [comment]
Hi,
Any update on this?

**Comment by kstenerud** [comment]
I removed parent process name in the latest commit, so this should no longer be a problem.
